### PR TITLE
add suspend workaround

### PR DESCRIPTION
**Pull request by aarron-lee**
describe workaround for devices that are having issues with suspend

### CODE REVIEW

**Comment by hbbit-dev** [comment]
@aarron-lee is this after swapping an ROG Ally SSD already containing ChimeraOS to a Legion Go?
I've seen this issue but only after people have swapped SSDs from a different device running ChimeraOS. Realistically it should be recommended to wipe your SSD first. While Linux installs can be transferred, the ROG and Go require different sets of workarounds to fix their different issues, the Ally guide I have even includes guides for installing kernels which would not work on the Legion Go at all.

If this is after an SSD swap from another device, I'd change the title to something along the lines of "how to fix suspend issues after SSD swap" with it's description mentioning that this should fix issues with migrating SSDs pre-installed with ChimeraOS, and the guide should probably mention as a disclaimer that it is recommended to start with a fresh installation. 

If you wanna make the edits yourself feel free, otherwise I'll make them tomorrow afternoon and merge it. Unless this is affecting users with fresh installs, I just havent seen that reported yet. I appreciate the PR!

**Comment by aarron-lee** [comment]
My impression is that the person who originally reported the problem had done a fresh install. Let me follow up with the user on discord and confirm

**Comment by aarron-lee** [comment]
Confirmed that it was a clean install of chimeraOS.

**Comment by hbbit-dev** [comment]
> Confirmed that it was a clean install of chimeraOS.

Gotcha, I was unaware that could happen with a fresh install. Merged

**Pull request merged**
